import Head from "next/head";
import "styles/globals.css";
import { ICON } from "../config";

const App = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Ruben Andino</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={ICON} />
      </Head>
      <Component {...pageProps} />
    </>
  );
};

export default App;
